### ISSUE TITLE
Exception in Application init method

### ISSUE THREAD

**Issue by poorvajappja** [gluonhq/gluon-samples#105]
> Task :run
Exception in Application init method
May 25, 2021 6:01:11 PM com.gluonhq.attach.util.Platform <clinit>
INFO: javafx.platform is not defined. Desktop will be assumed by default.
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application init method
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:895)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Input stream must not be null
	at javafx.graphics/javafx.scene.image.Image.validateInputStream(Image.java:1135)
	at javafx.graphics/javafx.scene.image.Image.<init>(Image.java:702)
Caused by: java.lang.RuntimeException: Exception in Application init method

	at com.gluonapplication.DrawerManager.buildDrawer(DrawerManager.java:25)
	at com.gluonapplication.GluonApplication.init(GluonApplication.java:21)
	at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:824)
	... 2 more
Exception running application com.gluonapplication.GluonApplication
Caused by: java.lang.NullPointerException: Input stream must not be null

> Task :run FAILED

Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-14.0.2\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**How can I solve this ?**

**Comment by jperedadnr** [comment]
Looks like you are not referring to any of the existing samples, are you?
It looks like you are missing an icon, make sure you have it under `src/main/resources`.
