### ISSUE TITLE
Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath

### ISSUE THREAD

**Issue by maxandersen** [gluonhq/gluon-samples#124]
trying to do hellofx build on osx using:

java --version
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

$GRAALVM_HOME/bin/native-image --version
GraalVM 21.2.0 Java 16 CE (Java Version 16.0.2+7-jvmci-21.2-b08)

```
[Tue Sep 28 14:12:49 CEST 2021][INFO] We will now compile your code for x86_64-apple-darwin. This may take some time.
[Tue Sep 28 14:12:52 CEST 2021][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Tue Sep 28 14:12:55 CEST 2021][INFO] [SUB] [hellofx.hellofx:8071]    classlist:   1,960.36 ms,  0.96 GB
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] [hellofx.hellofx:8071]        setup:     674.94 ms,  0.96 GB
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Error: Error parsing JNI configuration in /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/x86_64-darwin/gvm/jniconfig-x86_64-darwin.json:
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Error parsing JNI configuration in /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/x86_64-darwin/gvm/jniconfig-x86_64-darwin.json:
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Field java.net.Inet6Address.cached_scope_id not found. To allow unresolvable reflection configuration, use option -H:+AllowIncompleteClasspath
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Verify that the configuration matches the schema described in the -H:PrintFlags=+ output for option JNIConfigurationFiles.
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.doParseAndRegister(ConfigurationParserUtils.java:133)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.lambda$parseAndRegisterConfigurations$1(ConfigurationParserUtils.java:84)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:214)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:515)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at java.base/java.util.stream.IntPipeline.sum(IntPipeline.java:473)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.config.ConfigurationParserUtils.parseAndRegisterConfigurations(ConfigurationParserUtils.java:86)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.jni.access.JNIAccessFeature.afterRegistration(JNIAccessFeature.java:127)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.lambda$setupNativeImage$15(NativeImageGenerator.java:854)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:71)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:530)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:491)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:380)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:543)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:119)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] 	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:573)
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] [hellofx.hellofx:8071]      [total]:   2,698.53 ms,  0.96 GB
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] # Printing build artifacts to: /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/x86_64-darwin/gvm/HelloFX/hellofx.hellofx.build_artifacts.txt
[Tue Sep 28 14:12:56 CEST 2021][INFO] [SUB] Error: Image build request failed with exit status 1
[Tue Sep 28 14:12:56 CEST 2021][SEVERE] Process compile failed with result: 1
Check the log files under /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/x86_64-darwin/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[Tue Sep 28 14:12:56 CEST 2021][INFO] Logging process [compile] to file: /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/log/process-compile-1632831176170.log
[Tue Sep 28 14:12:56 CEST 2021][SEVERE] Compiling failed.
Check the log files under /Users/max/code/personal/demo/gluon-samples/HelloFX/target/gluonfx/x86_64-darwin/gvm/log
And please check https://docs.gluonhq.com/ for more information.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.126 s
[INFO] Finished at: 2021-09-28T14:12:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:gluonfx-maven-plugin:1.0.6:compile (default-cli) on project hellofx: Compiling failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
 ~/code/personal/demo/gluon-samples/HelloFX | master ·
```

**Comment by jperedadnr** [comment]
You are running with a GraalVM build based on JDK 16, which implies some changes (see https://github.com/gluonhq/substrate/issues/976). 
So far, Gluon GraalVM builds based on JDK 11 are recommended, see https://docs.gluonhq.com/#_platforms.
