### ISSUE TITLE
Error pushNotification Android

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluon-samples#137]
>02-04 12:24:20.866  7498  7523 D GraalCompiled: Feb 04, 2022 12:24:20 PM com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService readGoogleServicesConfiguration
02-04 12:24:20.866  7498  7523 D GraalCompiled: WARNING: Failed to read google-services.json. Make sure to add the file to the folder: src/android/resources
02-04 12:24:20.866  7498  7523 D GraalCompiled: java.lang.NullPointerException
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.UnicodeDetectingInputStream.fillBuf(UnicodeDetectingInputStream.java:65)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:104)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:51)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:71)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:49)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:112)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at javax.json.Json.createReader(Json.java:201)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService.readGoogleServicesConfiguration(AndroidPushNotificationsService.java:97)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService.register(AndroidPushNotificationsService.java:84)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.app.MGMobileApplication.lambda$initPushService$25(MGMobileApplication.java:1050)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at java.util.Optional.ifPresent(Optional.java:183)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.app.MGMobileApplication.initPushService(MGMobileApplication.java:1047)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.app.MGMobileApplication.beforeInitCustom(MGMobileApplication.java:821)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.app.MGMobileApplication.init_background(MGMobileApplication.java:413)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.app.MGMobileApplication.lambda$init$2(MGMobileApplication.java:374)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at it.wstech.mglib.util.MGUtils$2.run(MGUtils.java:243)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at java.lang.Thread.run(Thread.java:829)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
02-04 12:24:20.866  7498  7523 D GraalCompiled:         at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
02-04 12:24:20.866  7498  7523 D GraalCompiled:

The google-services.json file is in the required folder and also in the reflection file I have added the reference to com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService, but I always get the error reported. What can it depend on?

**Comment by websystemtechnology** [comment]
ok solved
