### ISSUE TITLE
Error pushNotification Android

### ISSUE THREAD

**Issue by websystemtechnology** [gluonhq/gluon-samples#139]
02-04 16:24:53.034 22224 22255 D GraalCompiled: Feb 04, 2022 4:24:53 PM com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService readGoogleServicesConfiguration
02-04 16:24:53.034 22224 22255 D GraalCompiled: WARNING: Failed to read google-services.json. Make sure to add the file to the folder: src/android/resources
02-04 16:24:53.034 22224 22262 D GraalGluon: ATTACH_DALVIK, tid = 22262, existed? 1, dalvikEnv at 0xb400007247057140
02-04 16:24:53.034 22224 22255 D GraalCompiled: java.lang.NullPointerException
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.UnicodeDetectingInputStream.fillBuf(UnicodeDetectingInputStream.java:65)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.UnicodeDetectingInputStream.detectEncoding(UnicodeDetectingInputStream.java:104)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.UnicodeDetectingInputStream.<init>(UnicodeDetectingInputStream.java:51)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.JsonParserImpl.<init>(JsonParserImpl.java:71)
> 02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.JsonReaderImpl.<init>(JsonReaderImpl.java:49)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at org.glassfish.json.JsonProviderImpl.createReader(JsonProviderImpl.java:112)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at javax.json.Json.createReader(Json.java:201)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService.readGoogleServicesConfiguration(AndroidPushNotificationsService.java:97)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at com.gluonhq.attach.pushnotifications.impl.AndroidPushNotificationsService.register(AndroidPushNotificationsService.java:84)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.app.MGMobileApplication.lambda$initPushService$25(MGMobileApplication.java:1051)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at java.util.Optional.ifPresent(Optional.java:183)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.app.MGMobileApplication.initPushService(MGMobileApplication.java:1047)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.app.MGMobileApplication.beforeInitCustom(MGMobileApplication.java:821)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.app.MGMobileApplication.init_background(MGMobileApplication.java:413)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.app.MGMobileApplication.lambda$init$2(MGMobileApplication.java:374)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at it.wstech.mglib.util.MGUtils$2.run(MGUtils.java:243)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at java.lang.Thread.run(Thread.java:829)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:596)
02-04 16:24:53.034 22224 22255 D GraalCompiled: 	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

The google-services.json file is in the required folder, but with the ./gradlew nativeBuild I have this error, as if the file was not present. Should I add it to the build.Gradle or elsewhere on the system? What should be done?

**Comment by websystemtechnology** [comment]
Solved.
Add in build.gralde -> resourcesList=["google-services.json"]
