### ISSUE TITLE
 Error Javafx Caused by: java.lang.UnsatisfiedLinkError: no glib-lite in java.library.path

### ISSUE THREAD

**Issue by alegithub72** [gluonhq/gluon-samples#142]
HI Guys,
the error is  when launch gluonfx:nativerun ; AudioClip.java  try to get file.wav resource whit this java code: 
```
ClassLoader classLoader = getClass().getClassLoader();
URL url = classLoader.getResource(sound);
return new AudioClip(url.toString());
```

I use graalvm=GraalVM 22.0.0.2 Java 17 CE  this the log:

```
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB] Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:901)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.lang.Thread.run(Thread.java:833)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.oracle.svm.core.windows.WindowsJavaThreads.osThreadStartRoutine(WindowsJavaThreads.java:140)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB] Caused by: java.lang.UnsatisfiedLinkError: no glib-lite in java.library.path
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.oracle.svm.core.jdk.NativeLibrarySupport.loadLibraryRelative(NativeLibrarySupport.java:132)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.lang.ClassLoader.loadLibrary(ClassLoader.java:47)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.lang.Runtime.loadLibrary0(Runtime.java:818)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.lang.System.loadLibrary(System.java:1989)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.glass.utils.NativeLibLoader.loadLibraryInternal(NativeLibLoader.java:166)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.glass.utils.NativeLibLoader.loadLibrary(NativeLibLoader.java:54)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaManager.lambda$new$0(NativeMediaManager.java:111)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.security.AccessController.doPrivileged(AccessController.java:125)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaManager.<init>(NativeMediaManager.java:108)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaManager$NativeMediaManagerInitializer.<clinit>(NativeMediaManager.java:78)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaManager.getDefaultInstance(NativeMediaManager.java:90)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmedia.MediaManager.canPlayProtocol(MediaManager.java:78)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmedia.locator.Locator.<init>(Locator.java:240)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaAudioClip.<init>(NativeMediaAudioClip.java:53)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.NativeMediaAudioClip.load(NativeMediaAudioClip.java:63)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmediaimpl.AudioClipProvider.load(AudioClipProvider.java:66)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.media.jfxmedia.AudioClip.load(AudioClip.java:135)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at javafx.scene.media.AudioClip.<init>(AudioClip.java:83)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at sa.fx.draugths.BCDraugthsApp.buildMedia(BCDraugthsApp.java:180)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at sa.fx.draugths.BCDraugthsApp.drawStartScreen(BCDraugthsApp.java:266)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at sa.fx.draugths.BCDraugthsApp.start(BCDraugthsApp.java:128)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at java.security.AccessController.doPrivileged(AccessController.java:107)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST_Runnable_run_16403f8d32adb631126daa893e5e80085c5d6325(JNIJavaCallWrappers.java:0)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
[lun apr 11 20:54:30 CEST 2022][INFO] [SUB]     at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
```

I put also resource new path extension to be sure to load it but there is stiil a problem???  my pom.xml:

```
            <plugin>
                <groupId>com.gluonhq</groupId>
                <artifactId>gluonfx-maven-plugin</artifactId>
                <version>1.0.13</version>
                <configuration>
                     <target>host</target>
                     <mainClass>sa.fx.draugths.BCDraugthsApp</mainClass>
					 <resourcesList>.*\\.mp3$,.*\\.wav$,.*\\.properties$</resourcesList>
                </configuration>
            </plugin>
```

**Comment by jperedadnr** [comment]
Media is not supported with native-image on Windows yet, see https://docs.gluonhq.com/#_platforms (table 3).

**Comment by alegithub72** [comment]
Tahks, 
is possible to build x86_64 apk for android??
I succefully run android (look [gluon checkerfx](https://github.com/alegithub72/checkersjavafx/tree/gluon)) but but run only on arm64 device but not found a simulator that run it ??

**Comment by jperedadnr** [comment]
No, not for now. If you want to run on simulator you might need an `arm64` image.
This is too old but it should work with the new GluonFX plugin and your APK for Android AArch64: https://stackoverflow.com/questions/44538097/export-javafx-project-to-android/44544233#44544233. I've also tried once BlueStacks.

**Comment by alegithub72** [comment]
I succeded to deploy on my Physical device _**Galaxy A20**_  and **_Mi Lite 10T_**  run on my devices, IoI.
I  prefer to debug on emulator .
 The old device image with arm64  don't run, the compatible 30 (that have no matter about CPU) type get ABI error on install 

I create  android 12 , API 31 and x86_64  and install the apk but on debug I get:

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: checkersfx.chekcersfx, PID: 9764
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libsubstrate.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
        at java.lang.System.loadLibrary(System.java:1656)
        at com.gluonhq.helloandroid.MainActivity.surfaceCreated(MainActivity.java:111)
        at android.view.SurfaceView.updateSurface(SurfaceView.java:1184)
        at android.view.SurfaceView.lambda$new$0$SurfaceView(SurfaceView.java:175)
        at android.view.SurfaceView$$ExternalSyntheticLambda2.onPreDraw(Unknown Source:2)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:1093)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3300)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2126)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8653)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
        at android.view.Choreographer.doCallbacks(Choreographer.java:845)
        at android.view.Choreographer.doFrame(Choreographer.java:780)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1022)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

What I need ???
