### ISSUE TITLE
Error Rest Provider

### ISSUE THREAD

**Issue by Hitzui** [gluonhq/gluon-samples#167]
Error to sample rest provider json url

`Exception in thread "DataProviderThread-0" java.lang.ExceptionInInitializerError
2023-05-19 22:58:23.470 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.gluonhq.connect.converter.JsonIterableInputConverter.iterator(JsonIterableInputConverter.java:136)
2023-05-19 22:58:23.470 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.gluonhq.connect.provider.RestListDataReader.iterator(RestListDataReader.java:80)
2023-05-19 22:58:23.470 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.gluonhq.connect.provider.DataProvider.lambda$retrieveList$23(DataProvider.java:206)
2023-05-19 22:58:23.471 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2023-05-19 22:58:23.471 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2023-05-19 22:58:23.471 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.lang.Thread.run(Thread.java:833)
2023-05-19 22:58:23.472 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
2023-05-19 22:58:23.472 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
2023-05-19 22:58:23.472 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  Caused by: javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.InstantiationException: org.glassfish.json.JsonProviderImpl
2023-05-19 22:58:23.472 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at javax.json.spi.JsonProvider.provider(JsonProvider.java:78)
2023-05-19 22:58:23.473 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at javax.json.Json.createReaderFactory(Json.java:215)
2023-05-19 22:58:23.473 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at com.gluonhq.impl.connect.converter.JsonUtil.<clinit>(JsonUtil.java:48)
2023-05-19 22:58:23.473 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	... 8 more
2023-05-19 22:58:23.473 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  Caused by: java.lang.InstantiationException: org.glassfish.json.JsonProviderImpl
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.lang.Class.newInstance(DynamicHub.java:639)
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at javax.json.spi.JsonProvider.provider(JsonProvider.java:73)
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	... 10 more
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  Caused by: java.lang.NoSuchMethodException: org.glassfish.json.JsonProviderImpl.<init>()
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.lang.Class.getConstructor0(DynamicHub.java:3585)
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	at java.lang.Class.newInstance(DynamicHub.java:626)
2023-05-19 22:58:23.474 28782-28946 GraalCompiled           com.jomirose.app.gluon               D  	... 11 more`

**Comment by Hitzui** [comment]
`Exception in thread "DataProviderThread-0" java.lang.ExceptionInInitializerError
at com.gluonhq.connect.converter.JsonIterableInputConverter.iterator(JsonIterableInputConverter.java:136)
at com.gluonhq.connect.provider.RestListDataReader.iterator(RestListDataReader.java:80)
at com.gluonhq.connect.provider.DataProvider.lambda$retrieveList$23(DataProvider.java:206)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.lang.Thread.run(Thread.java:833)
at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl could not be instantiated: java.lang.InstantiationException: org.glassfish.json.JsonProviderImpl
at javax.json.spi.JsonProvider.provider(JsonProvider.java:78)
at javax.json.Json.createReaderFactory(Json.java:215)
at com.gluonhq.impl.connect.converter.JsonUtil.<clinit>(JsonUtil.java:48)
... 8 more
Caused by: java.lang.InstantiationException: org.glassfish.json.JsonProviderImpl
at java.lang.Class.newInstance(DynamicHub.java:639)
at javax.json.spi.JsonProvider.provider(JsonProvider.java:73)
... 10 more
Caused by: java.lang.NoSuchMethodException: org.glassfish.json.JsonProviderImpl.<init>()
at java.lang.Class.getConstructor0(DynamicHub.java:3585)
at java.lang.Class.newInstance(DynamicHub.java:626)
... 11 more`
