### ISSUE TITLE
Gluon Mobile Gradle based project build issues 

### ISSUE THREAD

**Issue by UltraBurstXD** [gluonhq/gluon-samples#64]
I'm trying to convert a Maven project generated on Gluon Start website in Gradle project (I didn't test it on Maven build tool). I'm getting many errors:
**Exception in Application start method
java.lang.reflect.InvocationTargetException
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:464)
at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:363)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at java.base/sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:1051)
Caused by: java.lang.RuntimeException: Exception in Application start method
at javafx.graphics/com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Input stream must not be null
at javafx.graphics/javafx.scene.image.Image.validateInputStream(Image.java:1135)
at javafx.graphics/javafx.scene.image.Image.(Image.java:702)
at com.simple.Test.Test.lambda$init$1(Test.java:44)
at com.gluonhq.impl.charm.glisten.util.CachedFactory.get(CachedFactory.java:32)
at com.gluonhq.charm.glisten.application.MobileApplication.doSwitchView(MobileApplication.java:723)
at com.gluonhq.charm.glisten.application.MobileApplication.switchView(MobileApplication.java:477)
at com.gluonhq.charm.glisten.application.MobileApplication.switchView(MobileApplication.java:452)
at com.gluonhq.charm.glisten.application.MobileApplication.continueInit(MobileApplication.java:268)
at com.gluonhq.charm.glisten.application.MobileApplication.start(MobileApplication.java:232)
at javafx.graphics/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
... 1 more
Exception running application com.simple.Test.Test
Exception in thread "JavaFX Application Thread" java.lang.IllegalStateException: This operation is permitted on the event thread only; currentThread = JavaFX Application Thread
at javafx.graphics/com.sun.glass.ui.Application.checkEventThread(Application.java:441)
at javafx.graphics/com.sun.glass.ui.Application.isNestedLoopRunning(Application.java:542)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.isNestedLoopRunning(QuantumToolkit.java:1201)
at javafx.graphics/com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:637)
at javafx.graphics/javafx.application.Platform.enterNestedEventLoop(Platform.java:291)
at com.gluonhq.charm.glisten.control.Dialog.lambda$installIntoMobileApplication$7(Dialog.java:609)
at javafx.base/com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:181)
at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
at javafx.base/javafx.beans.property.ReadOnlyBooleanWrapper.fireValueChangedEvent(ReadOnlyBooleanWrapper.java:101)
at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
at javafx.base/javafx.beans.property.BooleanPropertyBase$Listener.invalidated(BooleanPropertyBase.java:239)
at javafx.base/com.sun.javafx.binding.ExpressionHelper$Generic.fireValueChangedEvent(ExpressionHelper.java:348)
at javafx.base/com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:80)
at javafx.base/javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:104)
at javafx.base/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:111)
at javafx.base/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
at javafx.base/javafx.beans.property.BooleanProperty.setValue(BooleanProperty.java:81)
at com.gluonhq.charm.glisten.layout.Layer.show(Layer.java:285)
at com.gluonhq.charm.glisten.control.Dialog.showAndWait(Dialog.java:560)
at com.gluonhq.impl.charm.glisten.util.NagScreenPresenter.lambda$showDialog$1(NagScreenPresenter.java:77)
at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
at java.base/java.lang.Thread.run(Thread.java:832)**

> Task :runSingle FAILED

FAILURE: Build failed with an exception.

    What went wrong:
    Execution failed for task ':runSingle'.

    Process 'command '/usr/lib/jvm/bellsoft-java14-full-amd64/bin/java'' finished with non-zero exit value 1

Any solution pls? I did every thing well on build (that's what I think), I don't have any imports problem or missing dependencies... Here's the build:
~~~ Groovy
plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.0.9'
    id 'com.gluonhq.client-gradle-plugin' version '0.1.31'
    id 'idea'
}

repositories {
    mavenCentral()
    maven {
        url 'https://nexus.gluonhq.com/nexus/content/repositories/releases'
    }
}


mainClassName = 'com.simple.Simple'
dependencies {
    //implementation 'com.gluonhq:charm-glisten:5.0.2'
    implementation 'com.gluonhq:connect:2.0.1'
    implementation 'com.gluonhq:charm-glisten:6.0.5'
    idea.module.downloadSources = true;
    idea.module.downloadJavadoc = true;
}

javafx {
    version = '14.0.2'
    modules = [ 'javafx.controls' ]
}

gluonClient {
    // target = 'ios' // Uncomment to enable iOS
    // target = 'android' // Uncomment to enable Android
    attachConfig {
        version = "4.0.9"
        services 'display', 'lifecycle', 'statusbar', 'storage', 'keyboard', 'device'
    }
}
~~~

**Comment by jperedadnr** [comment]
I can't reproduce your issue. I created a project from [Gluon Start](https://start.gluon.io), added your build.gradle, settings.gradle, and it works fine from command line (`./gradlew clean run`).

Can you post a zip with your project?

**Comment by UltraBurstXD** [comment]
[Simple.zip](https://github.com/gluonhq/gluon-samples/files/5251727/Simple.zip)

**Comment by jperedadnr** [comment]
Your sample runs for me from command line (`./gradlew clean run`) just fine

**Comment by UltraBurstXD** [comment]
Please change the main class to: 'com.simple.Test.Test'
And execute the task again. I've forgotten to change It

**Comment by jperedadnr** [comment]
You said before you didn't modify the code from Gluon Start. That's not the case. The generated code runs just fine, so you have to fix whatever changes you may have done.

In your added code you are referring resources that don't exist at that package `com.simple.Test`. 

Anyway, this is an issue for StackOverflow, with tag `gluon-mobile` (if related to Gluon Mobile).

**Comment by UltraBurstXD** [comment]
Well, I only copied the code there, changed build tool and specified the main class... I didn't do nothing more.
