### ISSUE TITLE
FXML embedding and retrieving problem.

### ISSUE THREAD

**Issue by Srijan-Sengupta** [gluonhq/gluon-samples#73]
Hello,

I am totally new to this plugin. Though I have a bit of knowledge in JavaFX but not in gluon. So, I was using the Gluon Client plugin with FXML here is the project which is also an open source project : https://github.com/Srijan-Sengupta/Purulia-Pollution-Check

I have used Github actions. Here is the yaml file: https://github.com/Srijan-Sengupta/Purulia-Pollution-Check/blob/main/.github/workflows/maven.yml

When I run the executable, it gives this error:

resource:com/srijan/javafx/pollution/Main.fxml
Exception in Application start method
Exception in thread "main" java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:900)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:195)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: javafx.fxml.LoadException: 
com/srijan/javafx/pollution/Main.fxml

	at javafx.fxml.FXMLLoader.constructLoadException(FXMLLoader.java:2629)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2867)
	at javafx.fxml.FXMLLoader.processImport(FXMLLoader.java:2711)
	at javafx.fxml.FXMLLoader.processProcessingInstruction(FXMLLoader.java:2680)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2546)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2470)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3241)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3198)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3167)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3140)
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:3117)
	at javafx.fxml.FXMLLoader.load(FXMLLoader.java:3110)
	at com.srijan.javafx.pollution.Main.start(Main.java:17)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.security.AccessController.doPrivileged(AccessController.java:101)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_Runnable_2_0002erun_00028_00029V(JNIJavaCallWrappers.java:0)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(GtkApplication.java)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	... 3 more
Caused by: java.lang.ClassNotFoundException: javafx.scene.chart.CategoryAxis
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:233)
	at javafx.fxml.FXMLLoader.loadTypeForPackage(FXMLLoader.java:2935)
	at javafx.fxml.FXMLLoader.loadType(FXMLLoader.java:2924)
	at javafx.fxml.FXMLLoader.importClass(FXMLLoader.java:2865)
	... 23 more

How must I resolve this problem?

**Comment by jperedadnr** [comment]
See https://docs.gluonhq.com/client/#_reflectionlist, you need to add ` javafx.scene.chart.CategoryAxis` to the `reflectionList`.
