### ISSUE TITLE
Native-image building on Windows currently only supports target architecture: AMD64

### ISSUE THREAD

**Issue by liudonghua123** [gluonhq/gluon-samples#86]
I opened `Developer Command Prompt for VS 2019` and tried to execute `mvn client:build` under HelloFXML, but it failed with the following errors.

```shell
> mvn client:build
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellofxml >--------------------
[INFO] Building HelloFXML 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- client-maven-plugin:0.1.35:build (default-cli) @ hellofxml ---
[INFO] Scanning for projects...
[INFO]
[INFO] -------------------< com.gluonhq.samples:hellofxml >--------------------
[INFO] Building HelloFXML 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] >>> client-maven-plugin:0.1.35:compile (default-cli) > process-classes @ hellofxml >>>
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ hellofxml ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hellofxml ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] <<< client-maven-plugin:0.1.35:compile (default-cli) < process-classes @ hellofxml <<<
[INFO]
[INFO]
[INFO] --- client-maven-plugin:0.1.35:compile (default-cli) @ hellofxml ---
[Tue Dec 29 11:18:13 CST 2020][INFO] ==================== COMPILE TASK ====================
             _______  ___      __   __  _______  __    _
            |       ||   |    |  | |  ||       ||  |  | |
            |    ___||   |    |  | |  ||   _   ||   |_| |
            |   | __ |   |    |  |_|  ||  | |  ||       |
            |   ||  ||   |___ |       ||  |_|  ||  _    |
            |   |_| ||       ||       ||       || | |   |
            |_______||_______||_______||_______||_|  |__|

    Access to the latest docs, tips and tricks and more info on
    how to get support? Register your usage of Gluon Substrate now at

    https://gluonhq.com/activate



[Tue Dec 29 11:18:17 CST 2020][INFO] We will now compile your code for x86_64-microsoft-windows. This may take some time.
[Tue Dec 29 11:18:17 CST 2020][INFO] Downloading JavaFX static libs...

Download progress: 0.01 / 24.72M
Download progress: 2.48 / 24.72M
Download progress: 4.95 / 24.72M
Download progress: 7.42 / 24.72M
Download progress: 9.89 / 24.72M
Download progress: 12.37 / 24.72M
Download progress: 14.84 / 24.72M
Download progress: 17.31 / 24.72M
Download progress: 19.78 / 24.72M
Download progress: 22.26 / 24.72M
Download progress: 24.72 / 24.72M
[Tue Dec 29 11:19:27 CST 2020][INFO] JavaFX static libs downloaded successfully
[Tue Dec 29 11:19:48 CST 2020][INFO] [SUB] Warning: Ignoring server-mode native-image argument --no-server.
[Tue Dec 29 11:20:04 CST 2020][INFO] [SUB] [hellofx.hellofxml:22248]    classlist:  11,425.10 ms,  0.96 GB
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB] [hellofx.hellofxml:22248]        setup:   3,528.87 ms,  0.96 GB
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB] Error: Native-image building on Windows currently only supports target architecture: AMD64 (x86 unsupported)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB] Error: To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB] com.oracle.svm.core.util.UserError$UserException: Native-image building on Windows currently only supports target architecture: AMD64 (x86 unsupported)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB] To prevent native-toolchain checking provide command-line option -H:-CheckToolchain
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.core.util.UserError.abort(UserError.java:139)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.addSkipCheckingInfo(CCompilerInvoker.java:105)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.hosted.c.codegen.CCompilerInvoker.verifyCompiler(CCompilerInvoker.java:96)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:870)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:556)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:471)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
[Tue Dec 29 11:20:07 CST 2020][INFO] [SUB]      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
[Tue Dec 29 11:20:08 CST 2020][INFO] [SUB] Error: Image build request failed with exit status 1
[Tue Dec 29 11:20:08 CST 2020][INFO] Additional information: Objectfile should be called hellofx.hellofxml.obj but we didn't find that under D:\code\java\gluon-samples\HelloFXML\target\client\x86_64-windows\gvm
[INFO] ------------------------------------------------------------------------
[Tue Dec 29 11:20:08 CST 2020][SEVERE] Compiling failed.
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
Check the log files under D:\code\java\gluon-samples\HelloFXML\target\client\x86_64-windows\gvm\log
[INFO] Total time: 01:57 min
And please check https://docs.gluonhq.com/client/ for more information.
[INFO] Finished at: 2020-12-29T11:20:08+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.35:compile (default-cli) on project hellofxml: Compiling failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:01 min
[INFO] Finished at: 2020-12-29T11:20:08+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.gluonhq:client-maven-plugin:0.1.35:build (default-cli) on project hellofxml: Error, client:build failed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

```

ps: I am using `graalvm-ce-java11-20.3.0` now.

**Comment by funbiscuit** [comment]
Did you use x64 tools? As shown below:
![image](https://user-images.githubusercontent.com/9351181/106357951-57e72e00-631a-11eb-8db2-3fe53c49085f.png)

x86 is not supported yet (just as error message said)
